[build]
  command = "yarn build"
  publish = "public"

[functions]
  directory = "netlify/functions"

[dev]
  command = "yarn start:netlify-dev"
  port = 3000
  autoLaunch = false

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, s-maxage=31536000"
