const plugin = require(`tailwindcss/plugin`)

/** @type {import('tailwindcss/tailwind-config').TailwindConfig} */
module.exports = {
  content: [`./app/**/*.tsx`],
  theme: {
    colors: {
      current: `currentColor`,
      grass: {
        1: `var(--grass-1)`,
        2: `var(--grass-2)`,
        3: `var(--grass-3)`,
        4: `var(--grass-4)`,
        5: `var(--grass-5)`,
        6: `var(--grass-6)`,
        7: `var(--grass-7)`,
        8: `var(--grass-8)`,
        9: `var(--grass-9)`,
        10: `var(--grass-10)`,
        11: `var(--grass-11)`,
        12: `var(--grass-12)`,
        a: {
          1: `var(--grass-a-1)`,
          2: `var(--grass-a-2)`,
          3: `var(--grass-a-3)`,
          4: `var(--grass-a-4)`,
          5: `var(--grass-a-5)`,
          6: `var(--grass-a-6)`,
          7: `var(--grass-a-7)`,
          8: `var(--grass-a-8)`,
          9: `var(--grass-a-9)`,
          10: `var(--grass-a-10)`,
          11: `var(--grass-a-11)`,
          12: `var(--grass-a-12)`,
        },
        light: {
          1: `var(--grass-light-1)`,
          2: `var(--grass-light-2)`,
          3: `var(--grass-light-3)`,
          4: `var(--grass-light-4)`,
          5: `var(--grass-light-5)`,
          6: `var(--grass-light-6)`,
          7: `var(--grass-light-7)`,
          8: `var(--grass-light-8)`,
          9: `var(--grass-light-9)`,
          10: `var(--grass-light-10)`,
          11: `var(--grass-light-11)`,
          12: `var(--grass-light-12)`,
          a: {
            1: `var(--grass-light-a-1)`,
            2: `var(--grass-light-a-2)`,
            3: `var(--grass-light-a-3)`,
            4: `var(--grass-light-a-4)`,
            5: `var(--grass-light-a-5)`,
            6: `var(--grass-light-a-6)`,
            7: `var(--grass-light-a-7)`,
            8: `var(--grass-light-a-8)`,
            9: `var(--grass-light-a-9)`,
            10: `var(--grass-light-a-10)`,
            11: `var(--grass-light-a-11)`,
            12: `var(--grass-light-a-12)`,
          },
        },
        dark: {
          1: `var(--grass-dark-1)`,
          2: `var(--grass-dark-2)`,
          3: `var(--grass-dark-3)`,
          4: `var(--grass-dark-4)`,
          5: `var(--grass-dark-5)`,
          6: `var(--grass-dark-6)`,
          7: `var(--grass-dark-7)`,
          8: `var(--grass-dark-8)`,
          9: `var(--grass-dark-9)`,
          10: `var(--grass-dark-10)`,
          11: `var(--grass-dark-11)`,
          12: `var(--grass-dark-12)`,
          a: {
            1: `var(--grass-dark-a-1)`,
            2: `var(--grass-dark-a-2)`,
            3: `var(--grass-dark-a-3)`,
            4: `var(--grass-dark-a-4)`,
            5: `var(--grass-dark-a-5)`,
            6: `var(--grass-dark-a-6)`,
            7: `var(--grass-dark-a-7)`,
            8: `var(--grass-dark-a-8)`,
            9: `var(--grass-dark-a-9)`,
            10: `var(--grass-dark-a-10)`,
            11: `var(--grass-dark-a-11)`,
            12: `var(--grass-dark-a-12)`,
          },
        },
      },
      olive: {
        1: `var(--olive-1)`,
        2: `var(--olive-2)`,
        3: `var(--olive-3)`,
        4: `var(--olive-4)`,
        5: `var(--olive-5)`,
        6: `var(--olive-6)`,
        7: `var(--olive-7)`,
        8: `var(--olive-8)`,
        9: `var(--olive-9)`,
        10: `var(--olive-10)`,
        11: `var(--olive-11)`,
        12: `var(--olive-12)`,
        a: {
          1: `var(--olive-a-1)`,
          2: `var(--olive-a-2)`,
          3: `var(--olive-a-3)`,
          4: `var(--olive-a-4)`,
          5: `var(--olive-a-5)`,
          6: `var(--olive-a-6)`,
          7: `var(--olive-a-7)`,
          8: `var(--olive-a-8)`,
          9: `var(--olive-a-9)`,
          10: `var(--olive-a-10)`,
          11: `var(--olive-a-11)`,
          12: `var(--olive-a-12)`,
        },
        light: {
          1: `var(--olive-light-1)`,
          2: `var(--olive-light-2)`,
          3: `var(--olive-light-3)`,
          4: `var(--olive-light-4)`,
          5: `var(--olive-light-5)`,
          6: `var(--olive-light-6)`,
          7: `var(--olive-light-7)`,
          8: `var(--olive-light-8)`,
          9: `var(--olive-light-9)`,
          10: `var(--olive-light-10)`,
          11: `var(--olive-light-11)`,
          12: `var(--olive-light-12)`,
          a: {
            1: `var(--olive-light-a-1)`,
            2: `var(--olive-light-a-2)`,
            3: `var(--olive-light-a-3)`,
            4: `var(--olive-light-a-4)`,
            5: `var(--olive-light-a-5)`,
            6: `var(--olive-light-a-6)`,
            7: `var(--olive-light-a-7)`,
            8: `var(--olive-light-a-8)`,
            9: `var(--olive-light-a-9)`,
            10: `var(--olive-light-a-10)`,
            11: `var(--olive-light-a-11)`,
            12: `var(--olive-light-a-12)`,
          },
        },
        dark: {
          1: `var(--olive-dark-1)`,
          2: `var(--olive-dark-2)`,
          3: `var(--olive-dark-3)`,
          4: `var(--olive-dark-4)`,
          5: `var(--olive-dark-5)`,
          6: `var(--olive-dark-6)`,
          7: `var(--olive-dark-7)`,
          8: `var(--olive-dark-8)`,
          9: `var(--olive-dark-9)`,
          10: `var(--olive-dark-10)`,
          11: `var(--olive-dark-11)`,
          12: `var(--olive-dark-12)`,
          a: {
            1: `var(--olive-dark-a-1)`,
            2: `var(--olive-dark-a-2)`,
            3: `var(--olive-dark-a-3)`,
            4: `var(--olive-dark-a-4)`,
            5: `var(--olive-dark-a-5)`,
            6: `var(--olive-dark-a-6)`,
            7: `var(--olive-dark-a-7)`,
            8: `var(--olive-dark-a-8)`,
            9: `var(--olive-dark-a-9)`,
            10: `var(--olive-dark-a-10)`,
            11: `var(--olive-dark-a-11)`,
            12: `var(--olive-dark-a-12)`,
          },
        },
      },
      error: `var(--error)`,
    },
    fontFamily: {
      sans: [`Public Sans`, `sans-serif`],
    },
  },
  plugins: [
    plugin(({addUtilities, addVariant}) => {
      addVariant(`children`, `& > *`)

      addVariant(`light`, `@media (prefers-color-scheme: light)`)
      addVariant(`autofill`, [`&:-webkit-autofill`, `&:-webkit-autofill:hover`, `&:-webkit-autofill:focus`])

      addVariant(`radix-open`, `&[data-state="open"]`)
      addVariant(`radix-closed`, `&[data-state="closed"]`)
      addVariant(`radix-visible`, `&[data-state="visible"]`)
      addVariant(`radix-hidden`, `&[data-state="hidden"]`)
      addVariant(`radix-checked`, `&[data-state="checked"]`)
      addVariant(`radix-unchecked`, `&[data-state="unchecked"]`)

      addUtilities({
        ".hard-center": {
          position: `absolute`,
          left: `50%`,
          top: `50%`,
          transform: `translate(-50%, -50%)`,
        },

        ".increase-touch-target": {
          "&::before": {
            content: `""`,
            position: `absolute`,
            top: `50%`,
            left: `50%`,
            transform: `translate(-50%, -50%)`,
            width: `100%`,
            height: `100%`,
            minWidth: `32px`,
            minHeight: `32px`,
          },
        },

        ".force-light": {
          "--grass-1": `var(--grass-light-1)`,
          "--grass-2": `var(--grass-light-2)`,
          "--grass-3": `var(--grass-light-3)`,
          "--grass-4": `var(--grass-light-4)`,
          "--grass-5": `var(--grass-light-5)`,
          "--grass-6": `var(--grass-light-6)`,
          "--grass-7": `var(--grass-light-7)`,
          "--grass-8": `var(--grass-light-8)`,
          "--grass-9": `var(--grass-light-9)`,
          "--grass-10": `var(--grass-light-10)`,
          "--grass-11": `var(--grass-light-11)`,
          "--grass-12": `var(--grass-light-12)`,

          "--grass-a-1": `var(--grass-light-a-1)`,
          "--grass-a-2": `var(--grass-light-a-2)`,
          "--grass-a-3": `var(--grass-light-a-3)`,
          "--grass-a-4": `var(--grass-light-a-4)`,
          "--grass-a-5": `var(--grass-light-a-5)`,
          "--grass-a-6": `var(--grass-light-a-6)`,
          "--grass-a-7": `var(--grass-light-a-7)`,
          "--grass-a-8": `var(--grass-light-a-8)`,
          "--grass-a-9": `var(--grass-light-a-9)`,
          "--grass-a-10": `var(--grass-light-a-10)`,
          "--grass-a-11": `var(--grass-light-a-11)`,
          "--grass-a-12": `var(--grass-light-a-12)`,

          "--olive-1": `var(--olive-light-1)`,
          "--olive-2": `var(--olive-light-2)`,
          "--olive-3": `var(--olive-light-3)`,
          "--olive-4": `var(--olive-light-4)`,
          "--olive-5": `var(--olive-light-5)`,
          "--olive-6": `var(--olive-light-6)`,
          "--olive-7": `var(--olive-light-7)`,
          "--olive-8": `var(--olive-light-8)`,
          "--olive-9": `var(--olive-light-9)`,
          "--olive-10": `var(--olive-light-10)`,
          "--olive-11": `var(--olive-light-11)`,
          "--olive-12": `var(--olive-light-12)`,

          "--olive-a-1": `var(--olive-light-a-1)`,
          "--olive-a-2": `var(--olive-light-a-2)`,
          "--olive-a-3": `var(--olive-light-a-3)`,
          "--olive-a-4": `var(--olive-light-a-4)`,
          "--olive-a-5": `var(--olive-light-a-5)`,
          "--olive-a-6": `var(--olive-light-a-6)`,
          "--olive-a-7": `var(--olive-light-a-7)`,
          "--olive-a-8": `var(--olive-light-a-8)`,
          "--olive-a-9": `var(--olive-light-a-9)`,
          "--olive-a-10": `var(--olive-light-a-10)`,
          "--olive-a-11": `var(--olive-light-a-11)`,
          "--olive-a-12": `var(--olive-light-a-12)`,

          "--error": `var(--error-light)`,

          color: `var(--olive-12)`,
        },

        ".force-dark": {
          "--grass-1": `var(--grass-dark-1)`,
          "--grass-2": `var(--grass-dark-2)`,
          "--grass-3": `var(--grass-dark-3)`,
          "--grass-4": `var(--grass-dark-4)`,
          "--grass-5": `var(--grass-dark-5)`,
          "--grass-6": `var(--grass-dark-6)`,
          "--grass-7": `var(--grass-dark-7)`,
          "--grass-8": `var(--grass-dark-8)`,
          "--grass-9": `var(--grass-dark-9)`,
          "--grass-10": `var(--grass-dark-10)`,
          "--grass-11": `var(--grass-dark-11)`,
          "--grass-12": `var(--grass-dark-12)`,

          "--grass-a-1": `var(--grass-dark-a-1)`,
          "--grass-a-2": `var(--grass-dark-a-2)`,
          "--grass-a-3": `var(--grass-dark-a-3)`,
          "--grass-a-4": `var(--grass-dark-a-4)`,
          "--grass-a-5": `var(--grass-dark-a-5)`,
          "--grass-a-6": `var(--grass-dark-a-6)`,
          "--grass-a-7": `var(--grass-dark-a-7)`,
          "--grass-a-8": `var(--grass-dark-a-8)`,
          "--grass-a-9": `var(--grass-dark-a-9)`,
          "--grass-a-10": `var(--grass-dark-a-10)`,
          "--grass-a-11": `var(--grass-dark-a-11)`,
          "--grass-a-12": `var(--grass-dark-a-12)`,

          "--olive-1": `var(--olive-dark-1)`,
          "--olive-2": `var(--olive-dark-2)`,
          "--olive-3": `var(--olive-dark-3)`,
          "--olive-4": `var(--olive-dark-4)`,
          "--olive-5": `var(--olive-dark-5)`,
          "--olive-6": `var(--olive-dark-6)`,
          "--olive-7": `var(--olive-dark-7)`,
          "--olive-8": `var(--olive-dark-8)`,
          "--olive-9": `var(--olive-dark-9)`,
          "--olive-10": `var(--olive-dark-10)`,
          "--olive-11": `var(--olive-dark-11)`,
          "--olive-12": `var(--olive-dark-12)`,

          "--olive-a-1": `var(--olive-dark-a-1)`,
          "--olive-a-2": `var(--olive-dark-a-2)`,
          "--olive-a-3": `var(--olive-dark-a-3)`,
          "--olive-a-4": `var(--olive-dark-a-4)`,
          "--olive-a-5": `var(--olive-dark-a-5)`,
          "--olive-a-6": `var(--olive-dark-a-6)`,
          "--olive-a-7": `var(--olive-dark-a-7)`,
          "--olive-a-8": `var(--olive-dark-a-8)`,
          "--olive-a-9": `var(--olive-dark-a-9)`,
          "--olive-a-10": `var(--olive-dark-a-10)`,
          "--olive-a-11": `var(--olive-dark-a-11)`,
          "--olive-a-12": `var(--olive-dark-a-12)`,

          "--error": `var(--error-dark)`,

          color: `var(--olive-12)`,
        },
      })
    }),
  ],
}
